logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace

spring:
  datasource:
    url: "jdbc:mysql://localhost:33069/springbatch?useUnicode=true&characterEncoding=utf8"
    username: "batch"
    password: "batch"
    driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true